/// Very small, v0.1-level generator that writes a single `api_client.dart`
/// file with `ApiClient` and `DefaultApi` classes.
///
/// Later this will be replaced/extended by a proper multi-file, per-resource
/// generator that inspects tags and operations from the OpenAPI spec.
class ApiClientClassGenerator {
  static String generate({
    required String packageImport,
    required String defaultApiMethods,
    Set<String>? modelImports,
    String? customAdapterType,
  }) {
    // For now we generate a minimal client that operates on `Map<String, dynamic>`
    // and demonstrates how generated code should use `ApiClientConfig` and
    // `HttpRequest` / `HttpClientAdapter`.
    
    final importsBuffer = StringBuffer();
    importsBuffer.writeln("import 'dart:async';");
    importsBuffer.writeln("import 'dart:convert';");
    importsBuffer.writeln();
    importsBuffer.writeln("import '$packageImport';");
    
    // Add model imports
    if (modelImports != null && modelImports.isNotEmpty) {
      importsBuffer.writeln();
      for (final importPath in modelImports) {
        importsBuffer.writeln("import '$importPath';");
      }
    }
    
    // Generate custom adapter documentation if needed
    String customAdapterDoc = '';
    if (customAdapterType != null && customAdapterType.isNotEmpty) {
      customAdapterDoc = '''

/// Custom HTTP adapter support
///
/// This client was generated with a custom adapter type: `$customAdapterType`.
/// To use this client, you must provide an instance of `$customAdapterType`
/// that implements `HttpClientAdapter` when creating `ApiClientConfig`:
///
/// ```dart
/// final customAdapter = $customAdapterType(); // Your custom adapter instance
/// final config = ApiClientConfig(
///   baseUrl: Uri.parse('https://api.example.com'),
///   httpClientAdapter: customAdapter,
/// );
/// final client = ApiClient(config);
/// ```
///
/// Make sure your `$customAdapterType` class implements `HttpClientAdapter`:
/// ```dart
/// class $customAdapterType implements HttpClientAdapter {
///   @override
///   Future<HttpResponse> send(HttpRequest request) async {
///     // Your implementation
///   }
/// }
/// ```
''';
    }
    
    return '''
// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// This file was generated by dart_swagger_to_api_client.

${importsBuffer.toString()}
$customAdapterDoc
/// Main entry point for working with the API.
class ApiClient {
  ApiClient(this._config);

  final ApiClientConfig _config;

  /// Default resource group.
  ///
  /// Future versions will split endpoints into multiple resource classes
  /// (e.g. UsersApi, OrdersApi) based on tags from the OpenAPI spec.
  DefaultApi get defaultApi => DefaultApi(_config);

  /// Closes the underlying HTTP client adapter.
  ///
  /// This should be called when the client is no longer needed to free up
  /// resources. Some adapters (e.g., DioHttpClientAdapter) may need explicit
  /// cleanup.
  Future<void> close() async {
    await _config.httpClientAdapter.close();
  }

  /// Creates a scoped client with additional headers.
  ///
  /// Returns a new [ApiClient] instance that uses the same configuration
  /// but with additional headers merged into the default headers.
  /// Headers from [additionalHeaders] override existing headers with the same key.
  ///
  /// Example:
  /// ```dart
  /// final scopedClient = client.withHeaders({'X-Request-ID': '123'});
  /// // All requests from scopedClient will include X-Request-ID header
  /// ```
  ApiClient withHeaders(Map<String, String> additionalHeaders) {
    final mergedHeaders = <String, String>{
      ..._config.defaultHeaders,
      ...additionalHeaders,
    };
    final newConfig = _config.copyWith(
      defaultHeaders: mergedHeaders,
    );
    return ApiClient(newConfig);
  }
}

/// Very small example of a resource class.
///
/// In v0.1 it only exposes a single generic `getRaw` method for demonstration.
class DefaultApi {
  DefaultApi(this._config);

  final ApiClientConfig _config;

$defaultApiMethods
}
''';
  }
}

