/// Very small, v0.1-level generator that writes a single `api_client.dart`
/// file with `ApiClient` and `DefaultApi` classes.
///
/// Later this will be replaced/extended by a proper multi-file, per-resource
/// generator that inspects tags and operations from the OpenAPI spec.
class ApiClientClassGenerator {
  static String generate({
    required String packageImport,
    required String defaultApiMethods,
  }) {
    // For now we generate a minimal client that operates on `Map<String, dynamic>`
    // and demonstrates how generated code should use `ApiClientConfig` and
    // `HttpRequest` / `HttpClientAdapter`.
    return '''
// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// This file was generated by dart_swagger_to_api_client.

import '$packageImport';

/// Main entry point for working with the API.
class ApiClient {
  ApiClient(this._config);

  final ApiClientConfig _config;

  /// Default resource group.
  ///
  /// Future versions will split endpoints into multiple resource classes
  /// (e.g. UsersApi, OrdersApi) based on tags from the OpenAPI spec.
  DefaultApi get defaultApi => DefaultApi(_config);
}

/// Very small example of a resource class.
///
/// In v0.1 it only exposes a single generic `getRaw` method for demonstration.
class DefaultApi {
  DefaultApi(this._config);

  final ApiClientConfig _config;

$defaultApiMethods
}
''';
  }
}

