/// Configuration for models generated by `dart_swagger_to_models`.
///
/// This represents the structure of `dart_swagger_to_models.yaml` that
/// `dart_swagger_to_api_client` needs to read to understand where models
/// are located and how they are named.
class ModelsConfig {
  ModelsConfig({
    this.outputDir,
    this.defaultStyle,
    Map<String, SchemaOverride>? schemas,
  }) : schemas = Map.unmodifiable(schemas ?? const {});

  /// Directory where models are generated (default: `lib/models`).
  final String? outputDir;

  /// Default generation style (e.g., `plain_dart`, `json_serializable`, `freezed`).
  final String? defaultStyle;

  /// Schema-specific overrides (custom class names, field names, etc.).
  final Map<String, SchemaOverride> schemas;
}

/// Override configuration for a specific schema.
class SchemaOverride {
  SchemaOverride({
    this.className,
    Map<String, String>? fieldNames,
    Map<String, String>? typeMapping,
  })  : fieldNames = Map.unmodifiable(fieldNames ?? const {}),
        typeMapping = Map.unmodifiable(typeMapping ?? const {});

  /// Custom class name for this schema (overrides default PascalCase conversion).
  final String? className;

  /// Field name mappings (JSON key → Dart field name).
  final Map<String, String> fieldNames;

  /// Type mappings (OpenAPI type → Dart type).
  final Map<String, String> typeMapping;
}
