// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// This file was generated by dart_swagger_to_api_client.

import 'dart:async';
import 'dart:convert';

import 'package:dart_swagger_to_api_client/dart_swagger_to_api_client.dart';


/// Main entry point for working with the API.
class ApiClient {
  ApiClient(this._config);

  final ApiClientConfig _config;

  /// Default resource group.
  ///
  /// Future versions will split endpoints into multiple resource classes
  /// (e.g. UsersApi, OrdersApi) based on tags from the OpenAPI spec.
  DefaultApi get defaultApi => DefaultApi(_config);

  /// Closes the underlying HTTP client adapter.
  ///
  /// This should be called when the client is no longer needed to free up
  /// resources. Some adapters (e.g., DioHttpClientAdapter) may need explicit
  /// cleanup.
  Future<void> close() async {
    await _config.httpClientAdapter.close();
  }

  /// Creates a scoped client with additional headers.
  ///
  /// Returns a new [ApiClient] instance that uses the same configuration
  /// but with additional headers merged into the default headers.
  /// Headers from [additionalHeaders] override existing headers with the same key.
  ///
  /// Example:
  /// ```dart
  /// final scopedClient = client.withHeaders({'X-Request-ID': '123'});
  /// // All requests from scopedClient will include X-Request-ID header
  /// ```
  ApiClient withHeaders(Map<String, String> additionalHeaders) {
    final mergedHeaders = <String, String>{
      ..._config.defaultHeaders,
      ...additionalHeaders,
    };
    return ApiClient(
      ApiClientConfig(
        baseUrl: _config.baseUrl,
        defaultHeaders: mergedHeaders,
        timeout: _config.timeout,
        auth: _config.auth,
        httpClientAdapter: _config.httpClientAdapter,
        httpClient: _config.httpClient,
      ),
    );
  }
}

/// Very small example of a resource class.
///
/// In v0.1 it only exposes a single generic `getRaw` method for demonstration.
class DefaultApi {
  DefaultApi(this._config);

  final ApiClientConfig _config;

  /// Generated from GET /users
  Future<List<Map<String, dynamic>>> getUsers({}) async {
    const _rawPath = '/users';
    final _path = '/users';

    final queryParameters = <String, String>{};
    final auth = _config.auth;
    if (auth?.apiKey != null) {
      queryParameters['api_key'] = auth!.apiKey!;
    }
    final uri = _config.baseUrl.replace(path: _path, queryParameters: queryParameters.isEmpty ? null : queryParameters,);

    final headers = <String, String>{
      ..._config.defaultHeaders,
    };

    final request = HttpRequest(
      method: 'GET',
      url: uri,
      headers: headers,
      timeout: _config.timeout,
    );

    final response = await _config.httpClientAdapter.send(request);

    if (response.statusCode == 401 || response.statusCode == 403) {
      throw ApiAuthException('Unauthorized request to $ _rawPath',
          statusCode: response.statusCode);
    }
    if (response.statusCode >= 500) {
      throw ApiServerException('Server error on $ _rawPath',
          statusCode: response.statusCode);
    }
    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw ApiClientException('Request failed for $ _rawPath',
          statusCode: response.statusCode);
    }

    final list = jsonDecode(response.body) as List<dynamic>;
    return list.cast<Map<String, dynamic>>();
  }

}
